"""user table add

Revision ID: 4dda23410d4a
Revises: 5b4439982ab4
Create Date: 2023-04-24 18:36:25.203208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dda23410d4a'
down_revision = '5b4439982ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_carts_cart_user_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_carts_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('cart_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_user', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_carts_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_carts_cart_user_users', 'users', ['cart_user'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
