"""user table add

Revision ID: 5b4439982ab4
Revises: 23e013ab7a08
Create Date: 2023-04-24 18:11:19.935184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4439982ab4'
down_revision = '23e013ab7a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
